### ISSUE TITLE
License in JS file is GPL but MIT license included in repo

### ISSUE THREAD

**Issue by mikegioia** [meetselva/fixed-table-rows-cols#25]
I just noticed that the license at the top of the javascript file (https://github.com/meetselva/fixed-table-rows-cols/blob/master/js/fixed_table_rc.js) is the GPL but the file you include in this repo is the MIT license.

Did you release this under both? Is there one you meant to use. I have no issue with and prefer the GPL but I'm going to make some updates for a project and wanted to honour the same license.

**Comment by meetselva** [comment]
Thanks. I have updated the copyright notice to MIT. Sorry for the delay in response.

**Comment by mikegioia** [comment]
Thanks :)
