### ISSUE TITLE
Heading of table contain two row

### ISSUE THREAD

**Issue by mag2000** [meetselva/fixed-table-rows-cols#28]
#I have table which have two rows of heading. The plugin is not working. Please if you have solution then let me know. sample of my table header

![tbill2](https://cloud.githubusercontent.com/assets/1167122/14638048/d238d4e8-064e-11e6-85b5-9539fd5d3210.png)

**Comment by meetselva** [comment]
The plugin was not tested with multiple headers, but with some modifications we can make it work. 

Could you post your html table in https://jsfiddle.net/ or somewhere I can look at?

**Comment by mag2000** [comment]
https://jsfiddle.net/y7L6gd2t/

**Comment by ddurose** [comment]
I am also interested in having a header that spans two rows. Any chance you could implement this in your plug-in? Thanks for considering.

**Comment by mag2000** [comment]
Waiting for your reply. Thanks for help

**Comment by meetselva** [comment]
Sorry about that, I did not had to change anything to make it work. I tried FF and IE Edge and it looked good. Test it in other browser and let me know.

https://jsfiddle.net/9jsb4oto/

**Comment by mag2000** [comment]
Thanks for your reply. May be i made some mistake will check and give feed back

Best Regards

**Comment by mag2000** [comment]
I check locally and it is working. 

Thanks for your prompt reply

**Comment by mag2000** [comment]
One problem with data. When we fixed the column it is not working.  I change the value 1 to fixed column on your above code and it is not working

Please can you fixed this as well.

**Comment by meetselva** [comment]
I have made a change to handle multiple tr in thead. Below is the exact code changes,

https://github.com/meetselva/fixed-table-rows-cols/blob/master/js/fixed_table_rc.js#L124-L130

For now, grab the code from the above URL or fiddle https://jsfiddle.net/ccLfz0ox/ . I need to test this change and will promote it in the next release.

Please test from your end and let me know how it looks.

**Comment by mag2000** [comment]
It is working fine. I graph from  https://jsfiddle.net/ccLfz0ox/ net the code

**Comment by mag2000** [comment]
Thanks for prompt reply and solution

**Comment by mag2000** [comment]
I compared both the code and found only one difference in code. I check both and both working. Which one you recommend

.css({height: cfg.height - 17}) (Jsfiddle)

.css({height: lc.ft_container.height() - 17}) (Github)

**Comment by meetselva** [comment]
Use the one from Github. The jsFiddle one must be using the old JS.

**Comment by omsysdesign** [comment]
Thanks Buddy your solutions is worked for me. your work has too much appreciable. 


many many thanks
